language: node_js
node_js:
- 11
cache:
  directories:
  - node_modules
script:
- yarn run build
- yarn test
deploy:
  provider: pages
  local-dir: "./build/"
  github-token: "$GITHUB_TOKEN"
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: K3pc1zr+dr6WLBIgaCmLLu8C5HhM4J/29iAkgvEkU5D1gV8XE+zi40mtQnwtlqU5Vc6yvru2TtNkpz6Fq7WBNbtvImebUC+COf7k8zfpDovjdGFedVMMpr6aba6b5UXy2Mtz6q4V8LrlA0SKUnIESRHmk2zrCfJHwnsaD7tJm4WzyYq+2evFhEtLdl96H8WjcGlwcuCYUVU1FPvJIpTxonDrEzhU9Z4XIMUvrXW3NX71FCOfWgV01vTuqZBO5w/M9kGjKGTfcSQA2Nrr8e5zGIbVGcHBic/fVhFzZtcGpNuRsrtVPd6I9OFb0neYrq33nhCyiCi7U0Sma+rIrG3mr5bOFlldrwGOv5GruE3eZvwbxdHxm9/86PAINHXxG1QRDTXoCWJPKc11PusxWfQzLOMaoAZPfHbzQ854L0nGkHi1tFfdi6nTWnnod4teM3IIU9t58MQ+xOO+0L4dKxWmObBqy3rH++5wsQTl9Pe9dMCvztEpAM726hIRyOGL7bAajzr0ikiLkWqKi3ngBxnk2jw+XRQW5+PsRPrSHW/Qsi3y3oZF1FZKMP4gMz0pp67qoaHgmxFeINU6FSMXGOs5FAxukDtnUrPVshAgPswxwYnySyMCiiBGZSkbJ1ClwicMh833C6+gOlv1x/LgCJ1/OQkS32Fe97EL9Dn8x6e7lS0=
